language: node_js
node_js:
- 4.0
before_install:
- npm install -g grunt-cli
install:
- npm install
script:
- "./node_modules/grunt-cli/bin/grunt test"
- npm test
after_success:
- "./create-release-tag.sh"
- "./update-release-branch.sh"
deploy:
  provider: heroku
  api_key:
    secure: h/9/Rcd41XVU4VYYeBoKKvG6uShEoDksCGGZ/2dgeY1f3tYnhGzzgL6TIkvhafwDbKk2Y4o6d/MI05K+s7lorf2uTKpr1To2o52hQqmb4YREPWruZtBqoRo5X4nCeN2oEdW+yJRH3jZDNUmwkPzjytqxkcUUUeDPHfz3+xCtSZk=
  app: govuk-prototype-kit
  on: master
notifications:
  email: false
sudo: false
env:
  global:
    secure: "itlYSNhbLY5fsRdFxEWRLFkdgRf8CV0dSlqjhAnNmB1sbpid3/QHwiOdgXjW29w5HLar3IgMedkrv3S0D+xCYqK5XkmixOY7zmeE0ixRxrMDDxmQB+3NSWITa14RTIlbQ+BKN5fTDq+h31KlUXkzWO+qi5wZMr4G30DH2GUUmIY="
